version: '3.9'
services:
  app:
    container_name: nest-js
    build:
      context: .
      dockerfile: ./src/docker/app/Dockerfile
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - my-network
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./src/docker/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
    restart: always
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
networks:
  my-network:
    name: my-network
    driver: bridge
volumes:
  postgres_data:
